services:
    jeddit:
        image: ghcr.io/whattheearl/jeddit:latest
        ports:
            - 5174:8080
        env_file:
            - ./.env.prod
        volumes:
            - jeddit:/home/jon/wte/jeddit/data

volumes:
    jeddit:
