name: build

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i
      - run: npx semantic-release
        env:
          GH_TOKEN: "${{ secrets.GHCR_SECRET }}"
